.TH "COVERDUMP" 1 "April 2021" "" "Cover Image Extractor"
.SH NAME
coverdump \- extracts cover images to files
.SH SYNOPSIS
coverdump [OPTIONS] <track>
.SH DESCRIPTION
.PP
coverdump takes an audio track and extracts all of its embedded cover images to individual files.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show a list of options and exit
.TP
\fB\-d\fR, \fB\-\-dir\fR=\fIDIRECTORY\fR
the target directory for the extracted image files; if none is given, the current working directory is used
.TP
\fB\-p\fR, \fB\-\-prefix\fR=\fIPREFIX\fR
a string to prefix to each extracted image file
.TP
\fB\-V\fR, \fB\-\-verbose\fR=\fIVERBOSITY\fR
The level of output to display. Choose between 'normal', 'quiet' and 'debug'.
.SH EXAMPLE
.LP
Extract the covert art embedded in track.flac to the images/ directory:
.IP
coverdump track.flac -d images/

.SH SEE ALSO
.BR audiotools-config (1),
.BR audiotools.cfg (5),
.BR cdda2track (1),
.BR cddainfo (1),
.BR cddaplay (1),
.BR covertag (1),
.BR coverview (1),
.BR dvda2track (1),
.BR dvdainfo (1),
.BR track2cdda (1),
.BR track2track (1),
.BR trackcat (1),
.BR trackcmp (1),
.BR trackinfo (1),
.BR tracklength (1),
.BR tracklint (1),
.BR trackplay (1),
.BR trackrename (1),
.BR tracksplit (1),
.BR tracktag (1),
.BR trackverify (1)
.SH AUTHOR
Brian Langenberger
