.TH "TRACKPLAY" 1 "April 2021" "" "Play Audio Tracks"
.SH NAME
trackplay \- plays audio tracks to speakers
.SH SYNOPSIS
trackplay [OPTIONS] <track 1> [track 2] ...
.SH DESCRIPTION
.PP
trackinfo takes a list of audio tracks and plays them to an available audio output device such as PulseAudio or the Open Sound System.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show a list of options and exit
.TP
\fB\-I\fR, \fB\-\-interactive\fR
run in interactive mode; this provides a text-based GUI and allows one to operate playback via keyboard and, on some terminals, mouse control
.TP
\fB\-o\fR, \fB\-\-output\fR=\fISYSTEM\fR
the output system to use, such as "PulseAudio" or "OSS"
.TP
\fB\-T\fR, \fB\-\-track\-replaygain\fR
apply track ReplayGain during playback, if present
.TP
\fB\-A\fR, \fB\-\-album\-replaygain\fR
apply album ReplayGain during playback, if present
.TP
\fB\-\-shuffle\fR
shuffle tracks randomly before playback
.TP
\fB\-V\fR, \fB\-\-verbose\fR=\fIVERBOSITY\fR
The level of output to display. Choose between 'normal', 'quiet' and 'debug'.
.SH PLAYBACK CONTROLS
.TS
tab(:);
l l l.
b'N / n':b'-':b'next track'
b'P / p':b'-':b'previous track'
b'Space':b'-':b'pause (non-interactive mode only)'
b'Esc / Q / q':b'-':b'quit'
.TE
.SH SEE ALSO
.BR audiotools-config (1),
.BR audiotools.cfg (5),
.BR cdda2track (1),
.BR cddainfo (1),
.BR cddaplay (1),
.BR coverdump (1),
.BR covertag (1),
.BR coverview (1),
.BR dvda2track (1),
.BR dvdainfo (1),
.BR track2cdda (1),
.BR track2track (1),
.BR trackcat (1),
.BR trackcmp (1),
.BR trackinfo (1),
.BR tracklength (1),
.BR tracklint (1),
.BR trackrename (1),
.BR tracksplit (1),
.BR tracktag (1),
.BR trackverify (1)
.SH AUTHOR
Brian Langenberger
