.TH "TRACKINFO" 1 "April 2021" "" "Track Information"
.SH NAME
trackinfo \- prints information and metadata from tracks
.SH SYNOPSIS
trackinfo [OPTIONS] <track 1> [track 2] ...
.SH DESCRIPTION
.PP
trackinfo takes a list of audio tracks and writes information about them to standard output. This includes track length, number of channels, sample rate, bits-per-sample, filename and additional metadata, if any.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show a list of options and exit
.TP
\fB\-n\fR, \fB\-\-no\-metadata\fR
do not print track metadata such as track name, album name and so forth
.TP
\fB\-L\fR, \fB\-\-low\-level\fR
display low-level metadata information such as ID3 frames, Vorbis comment pairs, and so on
.TP
\fB\-b\fR, \fB\-\-bitrate\fR
prints the average bitrate of the track in kilobytes-per-second instead of the usual track information
.TP
\fB\-%\fR, \fB\-\-percentage\fR
prints the percentage compression of the track instead of the usual track information
.TP
\fB\-C\fR, \fB\-\-channel\-assignment\fR
prints the track's channel assignment, if defined
.SH SEE ALSO
.BR audiotools-config (1),
.BR audiotools.cfg (5),
.BR cdda2track (1),
.BR cddainfo (1),
.BR cddaplay (1),
.BR coverdump (1),
.BR covertag (1),
.BR coverview (1),
.BR dvda2track (1),
.BR dvdainfo (1),
.BR track2cdda (1),
.BR track2track (1),
.BR trackcat (1),
.BR trackcmp (1),
.BR tracklength (1),
.BR tracklint (1),
.BR trackplay (1),
.BR trackrename (1),
.BR tracksplit (1),
.BR tracktag (1),
.BR trackverify (1)
.SH AUTHOR
Brian Langenberger
