.TH "TRACK2TRACK" 1 "April 2021" "" "Audio File Converter"
.SH NAME
track2track \- convert audio tracks
.SH SYNOPSIS
track2track [OPTIONS] <track 1> [track 2] ...
.SH DESCRIPTION
.PP
track2track converts audio tracks from one format to another.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show a list of options and exit
.TP
\fB\-I\fR, \fB\-\-interactive\fR
edit metadata and encoding options in interactive mode prior to converting tracks
.TP
\fB\-V\fR, \fB\-\-verbose\fR=\fIVERBOSITY\fR
The level of output to display. Choose between 'normal', 'quiet' and 'debug'.
.SH CONVERSION OPTIONS
.TP
\fB\-t\fR, \fB\-\-type\fR=\fITYPE\fR
The audio format to convert the given tracks to. For a list of available audio formats, try: -t help.
.TP
\fB\-q\fR, \fB\-\-quality\fR=\fIQUALITY\fR
The desired quality of the converted tracks. For a list of available quality modes for a given format, try: -q help
.TP
\fB\-d\fR, \fB\-\-dir\fR=\fIDIRECTORY\fR
The target directory for the converted tracks. If none is given, the current working directory is used. If the target directory does not exist, it will be created automatically. This option is not compatible with -o
.TP
\fB\-\-format\fR=\fISTRING\fR
The format string to use for new filenames. Template fields are replaced with metadata values when new tracks are created. All other text is left as-is. If this option is omitted, a default format string is used.
.TP
\fB\-o\fR, \fB\-\-output\fR=\fIFILENAME\fR
An explicit output filename for the converted track. With this option, only a single input track is allowed. It overrides the -d option and the default output filename.
.TP
\fB\-j\fR, \fB\-\-joint\fR=\fIPROCESSES\fR
The maximum number of tracks to convert at one time. If one has multiple CPUs or CPU cores, allowing track2track(1) to use all of them simultaneously can greatly increase encoding speed.
.SH FORMAT OPTIONS
.TP
\fB\-\-sample\-rate\fR=\fIRATE\fR
convert all output files to the given sample rate, in Hz
.TP
\fB\-\-channels\fR=\fICHANNELS\fR
convert all output files to the given number of channels
.TP
\fB\-\-bits\-per\-sample\fR=\fIBITS\fR
convert all output files to the given number of bits-per-sample
.SH CD LOOKUP OPTIONS
.TP
\fB\-M\fR, \fB\-\-metadata\-lookup\fR
perform metadata lookup for converted tracks
.TP
\fB\-\-musicbrainz\-server\fR=\fIHOSTNAME\fR
the MusicBrainz server name to query for metadata
.TP
\fB\-\-musicbrainz\-port\fR=\fIPORT\fR
the MusicBrainz port to query for metadata
.TP
\fB\-\-no\-musicbrainz\fR
don't query MusicBrainz for metadata
.TP
\fB\-\-freedb\-server\fR=\fIHOSTNAME\fR
the FreeDB server name to query for metadata
.TP
\fB\-\-freedb\-port\fR=\fIPORT\fR
the FreeDB port to query for metadata
.TP
\fB\-\-no\-freedb\fR
don't query FreeDB for metadata
.TP
\fB\-D\fR, \fB\-\-default\fR
When multiple metadata choices are available, select the first one automatically. This option has no effect when used with -I
.SH METADATA OPTIONS
.TP
\fB\-\-replay\-gain\fR
add ReplayGain metadata to newly created tracks
.TP
\fB\-\-no\-replay\-gain\fR
do not add ReplayGain metadata to newly created tracks
.SH EXAMPLES
.LP
Convert all the WAVE files in the current working directory to MP3s at the default quality:
.IP
track2track -t mp3 *.wav

.LP
Convert all of the FLAC files in sourcedir to Ogg Vorbis files and place them in targetdir:
.IP
track2track -t ogg -d targetdir sourcedir/*.flac

.LP
Convert all of the WAVE files in sourcedir to FLAC files, 2 at a time and at the highest possible compression (quality 8):
.IP
track2track -t flac -j 2 -q 8 sourcedir/*.wav

.SH FORMAT STRING FIELDS
.TS
tab(:);
| c   s |
| c | c |
| r | l |.
_
Template Fields
Key:Value
=
\fC%(track_number)2.2d\fR:the track's number on the CD
\fC%(track_total)d\fR:the total number of tracks on the CD
\fC%(album_number)d\fR:the CD's album number
\fC%(album_total)d\fR:the total number of CDs in the set
\fC%(album_track_number)s\fR:combination of album and track number
\fC%(track_name)s\fR:the track's name
\fC%(album_name)s\fR:the album's name
\fC%(artist_name)s\fR:the track's artist name
\fC%(performer_name)s\fR:the track's performer name
\fC%(composer_name)s\fR:the track's composer name
\fC%(conductor_name)s\fR:the track's conductor name
\fC%(media)s\fR:the track's source media
\fC%(ISRC)s\fR:the track's ISRC
\fC%(catalog)s\fR:the track's catalog number
\fC%(copyright)s\fR:the track's copyright information
\fC%(publisher)s\fR:the track's publisher
\fC%(year)s\fR:the track's publication year
\fC%(date)s\fR:the track's original recording date
\fC%(suffix)s\fR:the track's suffix
\fC%(basename)s\fR:the track's original name, without suffix
_
.TE
.SH SEE ALSO
.BR audiotools-config (1),
.BR audiotools.cfg (5),
.BR cdda2track (1),
.BR cddainfo (1),
.BR cddaplay (1),
.BR coverdump (1),
.BR covertag (1),
.BR coverview (1),
.BR dvda2track (1),
.BR dvdainfo (1),
.BR track2cdda (1),
.BR trackcat (1),
.BR trackcmp (1),
.BR trackinfo (1),
.BR tracklength (1),
.BR tracklint (1),
.BR trackplay (1),
.BR trackrename (1),
.BR tracksplit (1),
.BR tracktag (1),
.BR trackverify (1)
.SH AUTHOR
Brian Langenberger
